<!--
  This file was generated by ChronosGenerator  from model.uml.
  Manual modifications should be placed inside the protected regions.
-->
<!-- PROTECTED REGION ID(app/src/views/cms.tpl/Body) ENABLED START -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{$appTitle}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <base href="{$baseHref}">

    <link href="css/app.css" rel="stylesheet" media="screen">

    <script>
      document.write('<style media="all">#no-js { display: none; }</style>');
    </script>
  </head>

  <body class="dbootstrap">
    {if isset($error)}
    <div id="error" class="alert alert-error">
      <strong>Error!</strong> {$error}
    </div>
    {/if}

    <script>
      var appConfig = {$clientConfig};

      var dojoConfig = {
          has: {
              "dijit": true
          },
          baseUrl: '',
          locale: appConfig.uiLanguage,
          async: 1,
          isDebug: 0,
          packages: [
              { name: 'dojo', location: 'vendor/dojo/dojo' },
              { name: 'dijit', location: 'vendor/dojo/dijit' },
              { name: 'dojox', location: 'vendor/dojo/dojox' },
              { name: 'routed', location: 'vendor/sirprize/routed' },
              { name: 'dojomat', location: 'vendor/sirprize/dojomat' },
              { name: 'dgrid', location: 'vendor/sitepen/dgrid' },
              { name: 'xstyle', location: 'vendor/kriszyp/xstyle' },
              { name: 'put-selector', location: 'vendor/kriszyp/put-selector' },
              { name: 'ckeditor', location: 'vendor/ckeditor/ckeditor' },
              { name: 'elfinder', location: 'vendor/studio-42/elfinder' },
              { name: 'd3', location: 'http://d3js.org' },
              { name: 'trianglify', location: 'http://cdnjs.cloudflare.com/ajax/libs/trianglify/0.1.2' },

              { name: 'app', location: '.' }
          ],
          'routing-map': {
              pathPrefix: appConfig.pathPrefix
          }
      };
    </script>

    <script src="vendor/dojo/dojo/dojo.js"></script>

    <script>
      require(["app/js/App"], function (App) { new App({}, 'push'); });
    </script>

    <div id="no-js" class="alert alert-error">
      <strong>Warning!</strong> Please enable JavaScript in your browser.
    </div>

    <div id="wrap">
      <div id="push"></div>
    </div>
    <div id="footer">
      <div class="container">
        <p class="pull-right muted">created with
          <a href="http://sourceforge.net/projects/wcmf/" target="_blank">wCMF</a></p>
        <p class="muted">&copy; 2014</p>
      </div>
    </div>

  </body>
</html>
<!-- PROTECTED REGION END -->
