sudo: false

addons:
  apt:
    packages:
    - openjdk-8-jdk
    - ant

services:
  - mysql

language: php

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
    - TEST_DIR=$TRAVIS_BUILD_DIR/test WCMF_BASE_DIR=$TRAVIS_BUILD_DIR

matrix:
  include:
  - php: 7.2
  allow_failures:
  
before_script:
  - mysql -e 'CREATE DATABASE wcmf_testapp;'
  - composer self-update
  - composer install

  - cd $WCMF_BASE_DIR/build && ant generate && ant dist
  - chmod +x ../dist/vendor/phpunit/phpunit/phpunit

  - phantomjs --webdriver=8001 &

script:
  - cd $TEST_DIR &&  ../dist/vendor/phpunit/phpunit/phpunit --bootstrap bootstrap.php -c configuration.xml
