/**
 * This file was generated by ChronosGenerator wcmf-1.0.25.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
import DBSequence from '~/app/model/src/model/wcmf/DBSequence'
import Lock from '~/app/model/src/model/wcmf/Lock'
import Language from '~/app/model/src/model/wcmf/Language'
import Translation from '~/app/model/src/model/wcmf/Translation'
import Permission from '~/app/model/src/model/wcmf/Permission'
import User from '~/app/model/src/model/wcmf/User'
import UserConfig from '~/app/model/src/model/wcmf/UserConfig'
import Role from '~/app/model/src/model/wcmf/Role'

export default [
  DBSequence,
  Lock,
  Language,
  Translation,
  Permission,
  User,
  UserConfig,
  Role,
]