Vagrant.configure("2") do |config|
	
	# Specify the base box
	config.vm.box = "ubuntu/trusty64"
	
  # Setup synced folder
  config.vm.synced_folder "../", "/var/www/wcmf-default-app", create: true, group: "www-data", owner: "www-data"

  forward_port = ->(guest, host = guest) do
    config.vm.network :forwarded_port,
      guest: guest,
      host: host,
      auto_correct: true
  end

  forward_port[3306]  # mysql
  forward_port[80, 8080]  # apache
  forward_port[81, 8081]  # phpmyadmin

  # Shell provisioning
  config.vm.provision "shell" do |s|
    s.path = "provision/setup.sh"
  end
end