--
-- This file was generated by ChronosGenerator wcmf-1.0.10 from model.uml.
-- Manual modifications should be placed inside the protected regions.
--
--
-- Structure of Table `DBSequence`
--
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `DBSequence`;
CREATE TABLE `DBSequence` -- entityType=DBSequence tableId=_s2Ve4LTMEeOYkOsR5IzpsA
(
  `table` VARCHAR(255), -- columnId=_PsZYwP_DEeWzxP-Oi6uCUQ
  `id` INT(11), -- columnId=_QCBDcP_DEeWzxP-Oi6uCUQ
  PRIMARY KEY (`table`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `Lock`
--
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `Lock`;
CREATE TABLE `Lock` -- entityType=Lock tableId=_s73fILTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `objectid` VARCHAR(255), -- columnId=_EVGnsLTTEeOYkOsR5IzpsA
  `login` VARCHAR(255), -- columnId=_hAkZEDQ0EeSRmq5T8ey5JQ
  `created` DATETIME, -- columnId=_EZrlsLTTEeOYkOsR5IzpsA
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `Language`
-- A language for which a translation of the model can be created. The code is arbitrary but it is recommended to use the ISO language codes (en, de, it, ...).
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `Language`;
CREATE TABLE `Language` -- entityType=Language tableId=_s5AYYLTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `name` VARCHAR(255), -- columnId=_mThnQLTOEeOYkOsR5IzpsA
  `code` VARCHAR(255), -- columnId=_mWMgwLTOEeOYkOsR5IzpsA
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `Translation`
-- Instances of this class are used to localize entity attributes. Each instance defines a translation of one attribute of one entity into one language.
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `Translation`;
CREATE TABLE `Translation` -- entityType=Translation tableId=_tCKUYLTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `objectid` VARCHAR(255), -- columnId=_4sa_QLTQEeOYkOsR5IzpsA
  `attribute` VARCHAR(255), -- columnId=_4vqggLTQEeOYkOsR5IzpsA
  `translation` TEXT, -- columnId=_4zGPALTQEeOYkOsR5IzpsA
  `language` VARCHAR(255), -- columnId=_42VwQLTQEeOYkOsR5IzpsA
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `User`
--
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `User`;
CREATE TABLE `User` -- entityType=User tableId=_tJBxYLTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `login` VARCHAR(255), -- columnId=_P0GFcLTREeOYkOsR5IzpsA
  `password` VARCHAR(255), -- columnId=_P23FkLTREeOYkOsR5IzpsA
  `name` VARCHAR(255), -- columnId=_P5h_ELTREeOYkOsR5IzpsA
  `firstname` VARCHAR(255), -- columnId=_P8fMcLTREeOYkOsR5IzpsA
  `active` INT(1), -- columnId=_KXBDUMNyEeabSe-F2MKJtA
  `super_user` INT(1), -- columnId=_bUR1sMNyEeabSe-F2MKJtA
  `config` VARCHAR(255), -- columnId=_P_cZ0LTREeOYkOsR5IzpsA
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `UserConfig`
--
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `UserConfig`;
CREATE TABLE `UserConfig` -- entityType=UserConfig tableId=_tFTvALTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `fk_user_id` INT(11), -- columnId=_generated_fk_user_id_ referencedTable=User
  `name` VARCHAR(255), -- columnId=_1-0UELTREeOYkOsR5IzpsA
  `value` TEXT, -- columnId=_2AoR8LTREeOYkOsR5IzpsA
  PRIMARY KEY (`id`)
  ,KEY `fk_user_id` (`fk_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `Role`
--
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `Role`;
CREATE TABLE `Role` -- entityType=Role tableId=_s_A5wLTMEeOYkOsR5IzpsA
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `name` VARCHAR(255), -- columnId=_blxxgLTWEeOYkOsR5IzpsA
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `NMUserRole`
--
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `NMUserRole`;
CREATE TABLE `NMUserRole` -- entityType=NMUserRole tableId=_tM8BALTMEeOYkOsR5IzpsA
(
  `fk_role_id` INT(11), -- columnId=_generated_fk_role_id_ referencedTable=Role
  `fk_user_id` INT(11), -- columnId=_generated_fk_user_id_ referencedTable=User
  PRIMARY KEY (`fk_role_id`,`fk_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `Permission`
--
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `Permission`;
CREATE TABLE `Permission` -- entityType=Permission tableId=_VEQuMDkNEeSAepGYcnIyuw
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `resource` VARCHAR(255), -- columnId=_VEQuMTkNEeSAepGYcnIyuw
  `context` VARCHAR(255), -- columnId=_VEQuNTkNEeSAepGYcnIyuw
  `action` VARCHAR(255), -- columnId=_VEQuOTkNEeSAepGYcnIyuw
  `roles` VARCHAR(255), -- columnId=_dNmz4DkNEeSAepGYcnIyuw
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `Publisher`
-- A publisher publishes books.
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `Publisher`;
CREATE TABLE `Publisher` -- entityType=Publisher tableId=_BDrKMLU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `name` VARCHAR(255), -- columnId=_UsqjALU2EeORdpT3S9OOtw
  `created` DATETIME, -- columnId=_generated_created_
  `creator` VARCHAR(255), -- columnId=_generated_creator_
  `modified` DATETIME, -- columnId=_generated_modified_
  `last_editor` VARCHAR(255), -- columnId=_generated_last_editor_
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `Author`
--
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `Author`;
CREATE TABLE `Author` -- entityType=Author tableId=_BGWqwLU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `name` VARCHAR(255), -- columnId=_rq2WALU2EeORdpT3S9OOtw
  `created` DATETIME, -- columnId=_generated_created_
  `creator` VARCHAR(255), -- columnId=_generated_creator_
  `modified` DATETIME, -- columnId=_generated_modified_
  `last_editor` VARCHAR(255), -- columnId=_generated_last_editor_
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `Book`
-- A book is published by a publisher and consists of chapters.
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `Book`;
CREATE TABLE `Book` -- entityType=Book tableId=_BJe3QLU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `fk_publisher_id` INT(11), -- columnId=_generated_fk_publisher_id_ referencedTable=Publisher
  `title` VARCHAR(255), -- columnId=__mzRoLU3EeORdpT3S9OOtw
  `description` VARCHAR(255), -- columnId=__p_vkLU3EeORdpT3S9OOtw
  `year` VARCHAR(255), -- columnId=__svhkLU3EeORdpT3S9OOtw
  `created` DATETIME, -- columnId=_generated_created_
  `creator` VARCHAR(255), -- columnId=_generated_creator_
  `modified` DATETIME, -- columnId=_generated_modified_
  `last_editor` VARCHAR(255), -- columnId=_generated_last_editor_
  PRIMARY KEY (`id`)
  ,KEY `fk_publisher_id` (`fk_publisher_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `Chapter`
-- A book is divided into chapters. A chapter may contain subchapters.
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `Chapter`;
CREATE TABLE `Chapter` -- entityType=Chapter tableId=_BMnDwLU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `fk_chapter_id` INT(11), -- columnId=_generated_fk_chapter_id_ referencedTable=Chapter
  `fk_book_id` INT(11), -- columnId=_generated_fk_book_id_ referencedTable=Book
  `fk_author_id` INT(11), -- columnId=_generated_fk_author_id_ referencedTable=Author
  `name` VARCHAR(255), -- columnId=_kq-u8LU4EeORdpT3S9OOtw
  `content` TEXT, -- columnId=_njBmAPT-EeSdk57oe2HXMQ
  `created` DATETIME, -- columnId=_generated_created_
  `creator` VARCHAR(255), -- columnId=_generated_creator_
  `modified` DATETIME, -- columnId=_generated_modified_
  `last_editor` VARCHAR(255), -- columnId=_generated_last_editor_
  `sortkey_author` DECIMAL(41,30), -- columnId=sortkey_author
  `sortkey_book` DECIMAL(41,30), -- columnId=sortkey_book
  `sortkey_parentchapter` DECIMAL(41,30), -- columnId=sortkey_parentchapter
  `sortkey` DECIMAL(41,30), -- columnId=sortkey
  PRIMARY KEY (`id`)
  ,KEY `fk_chapter_id` (`fk_chapter_id`)
  ,KEY `fk_book_id` (`fk_book_id`)
  ,KEY `fk_author_id` (`fk_author_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `Image`
--
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `Image`;
CREATE TABLE `Image` -- entityType=Image tableId=_BQLVILU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `fk_chapter_id` INT(11), -- columnId=_generated_fk_chapter_id_ referencedTable=Chapter
  `fk_titlechapter_id` INT(11), -- columnId=_generated_fk_titlechapter_id_ referencedTable=Chapter
  `file` VARCHAR(255), -- columnId=_0UxuULU4EeORdpT3S9OOtw
  `created` DATETIME, -- columnId=_generated_created_
  `creator` VARCHAR(255), -- columnId=_generated_creator_
  `modified` DATETIME, -- columnId=_generated_modified_
  `last_editor` VARCHAR(255), -- columnId=_generated_last_editor_
  `sortkey_titlechapter` DECIMAL(41,30), -- columnId=sortkey_titlechapter
  `sortkey_normalchapter` DECIMAL(41,30), -- columnId=sortkey_normalchapter
  `sortkey` DECIMAL(41,30), -- columnId=sortkey
  PRIMARY KEY (`id`)
  ,KEY `fk_chapter_id` (`fk_chapter_id`)
  ,KEY `fk_titlechapter_id` (`fk_titlechapter_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `NMPublisherAuthor`
--
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `NMPublisherAuthor`;
CREATE TABLE `NMPublisherAuthor` -- entityType=NMPublisherAuthor tableId=_BTThoLU2EeORdpT3S9OOtw
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `fk_author_id` INT(11), -- columnId=_generated_fk_author_id_ referencedTable=Author
  `fk_publisher_id` INT(11), -- columnId=_generated_fk_publisher_id_ referencedTable=Publisher
  `sortkey_publisher` DECIMAL(41,30), -- columnId=sortkey_publisher
  `sortkey_author` DECIMAL(41,30), -- columnId=sortkey_author
  `sortkey` DECIMAL(41,30), -- columnId=sortkey
  PRIMARY KEY (`id`)
  ,KEY `fk_author_id` (`fk_author_id`)
  ,KEY `fk_publisher_id` (`fk_publisher_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
-- Structure of Table `NMBookBook`
--
-- version 1.0
-- init params database
--
DROP TABLE IF EXISTS `NMBookBook`;
CREATE TABLE `NMBookBook` -- entityType=NMBookBook tableId=_Cmrd8E0BEeWgTqa5Y3-hfQ
(
  `id` INT(11) NOT NULL, -- columnId=_generated_id_
  `fk_referencedbook_id` INT(11), -- columnId=_generated_fk_referencedbook_id_ referencedTable=Book
  `fk_referencingbook_id` INT(11), -- columnId=_generated_fk_referencingbook_id_ referencedTable=Book
  `sortkey_referencingbook` DECIMAL(41,30), -- columnId=sortkey_referencingbook
  `sortkey_referencedbook` DECIMAL(41,30), -- columnId=sortkey_referencedbook
  `sortkey` DECIMAL(41,30), -- columnId=sortkey
  PRIMARY KEY (`id`)
  ,KEY `fk_referencedbook_id` (`fk_referencedbook_id`)
  ,KEY `fk_referencingbook_id` (`fk_referencingbook_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
