/**
 * This file was generated by ChronosGenerator wcmf-1.0.10 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
import { EntityType } from '~/stores/model/meta/types'

import app_src_model_wcmf_DBSequence from '~/app/src/model/wcmf/DBSequence'
import app_src_model_wcmf_Lock from '~/app/src/model/wcmf/Lock'
import app_src_model_wcmf_Language from '~/app/src/model/wcmf/Language'
import app_src_model_wcmf_Translation from '~/app/src/model/wcmf/Translation'
import app_src_model_wcmf_User from '~/app/src/model/wcmf/User'
import app_src_model_wcmf_UserConfig from '~/app/src/model/wcmf/UserConfig'
import app_src_model_wcmf_Role from '~/app/src/model/wcmf/Role'
import app_src_model_wcmf_Permission from '~/app/src/model/wcmf/Permission'
import app_src_model_Publisher from '~/app/src/model/Publisher'
import app_src_model_Author from '~/app/src/model/Author'
import app_src_model_Book from '~/app/src/model/Book'
import app_src_model_Chapter from '~/app/src/model/Chapter'
import app_src_model_Image from '~/app/src/model/Image'

const types: EntityType[] = [
  new app_src_model_wcmf_DBSequence,
  new app_src_model_wcmf_Lock,
  new app_src_model_wcmf_Language,
  new app_src_model_wcmf_Translation,
  new app_src_model_wcmf_User,
  new app_src_model_wcmf_UserConfig,
  new app_src_model_wcmf_Role,
  new app_src_model_wcmf_Permission,
  new app_src_model_Publisher,
  new app_src_model_Author,
  new app_src_model_Book,
  new app_src_model_Chapter,
  new app_src_model_Image
]
export default types
