<?php
/**
 * This file was generated by ChronosGenerator wcmf-1.0.24.0001 from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model;

use wcmf\lib\model\Node;
// PROTECTED REGION ID(app/src/model/EntityBase.php/Import) ENABLED START
use wcmf\lib\core\ObjectFactory;
// PROTECTED REGION END

/**
 * EntityBase
 *
 * @var id
 * @var created (Date)
 * @var creator (String)
 * @var modified (Date)
 * @var last_editor (String)
 */
abstract class EntityBase extends Node {
// PROTECTED REGION ID(app/src/model/EntityBase.php/Body) ENABLED START
  /**
   * Set creator and created attribute on the node.
   */
  public function beforeInsert() {
    parent::beforeInsert();

    // set creation date on nodes with appropriate attribute
    $mapper = $this->getMapper();
    if ($mapper->hasAttribute('created')) {
      $this->setValue('created', date("Y-m-d H:i:s"));
    }
    // set creator on nodes with appropriate attribute
    if ($mapper->hasAttribute('creator')) {
      $session = ObjectFactory::getInstance('session');
      $authUserLogin = $session->getAuthUser();
      $this->setValue('creator', $authUserLogin);
    }
    $this->beforeUpdate();
  }

  /**
   * Set last_editor and modified attribute on the node.
   */
  public function beforeUpdate() {
    parent::beforeUpdate();

    // set modified date on nodes with appropriate attribute
    $mapper = $this->getMapper();
    if ($mapper->hasAttribute('modified')) {
      $this->setValue('modified', date("Y-m-d H:i:s"));
    }
    // set last_editor on nodes with appropriate attribute
    if ($mapper->hasAttribute('last_editor')) {
      $session = ObjectFactory::getInstance('session');
      $authUserLogin = $session->getAuthUser();
      $this->setValue('last_editor', $authUserLogin);
    }
  }
// PROTECTED REGION END
}
