<?php

/**
 * This file was generated by ChronosGenerator  from model.uml.
 * Manual modifications should be placed inside the protected regions.
 */
namespace app\src\model;

use wcmf\lib\model\Node;

use wcmf\lib\i18n\Message;
use wcmf\lib\persistence\ObjectId;

/**
 * EntityBase description:
 *
 * @author
 * @version 1.0
 */
class EntityBaseBase extends Node {

    /**
     * Constructor
     * @param oid ObjectId instance (optional)
     */
    public function __construct($oid=null) {
      if ($oid == null) {
        $oid = new ObjectId('EntityBase');
    }
      parent::__construct($oid);
    }

    /**
     * @see PersistentObject::getObjectDisplayName()
     */
    public function getObjectDisplayName() {
      return Message::get("EntityBase");
    }

    /**
     * @see PersistentObject::getObjectDescription()
     */
    public function getObjectDescription() {
      return Message::get("");
    }

    /**
     * @see PersistentObject::getValueDisplayName()
     */
    public function getValueDisplayName($name) {
      $displayName = $name;
      if (false) {}
      elseif ($name == 'id') { $displayName = Message::get("id"); }
      elseif ($name == 'created') { $displayName = Message::get("created"); }
      elseif ($name == 'creator') { $displayName = Message::get("creator"); }
      elseif ($name == 'modified') { $displayName = Message::get("modified"); }
      elseif ($name == 'last_editor') { $displayName = Message::get("last_editor"); }
      return $displayName;
    }

    /**
     * @see PersistentObject::getValueDescription()
     */
    public function getValueDescription($name) {
      $description = $name;
      if (false) {}
      elseif ($name == 'id') { $description = Message::get(""); }
      elseif ($name == 'created') { $description = Message::get(""); }
      elseif ($name == 'creator') { $description = Message::get(""); }
      elseif ($name == 'modified') { $description = Message::get(""); }
      elseif ($name == 'last_editor') { $description = Message::get(""); }
      return $description;
    }

}
?>
